# This file should contain all the record creation needed to seed the database with its default values.  # The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).  # # Examples: #   #   cities = City.create([{ :title => 'Chicago' }, { :title => 'Copenhagen' }]) #   Major.create(:title => 'Daley', :city => cities.first)
#
#
Author.create([{ :name => "Charles Dickens"}, {:name => "Leo Tolstoy"}, {:name => "Anton Checkov"}])
Article.create([{ :title => 'A Tale of Two Cities', :author => Author.find_by_name("Charles Dickens"), :edit_count => 0, :body => <<HEREE
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non pellentesque massa. Vestibulum in congue metus. Phasellus malesuada scelerisque dui vitae pretium. Phasellus quam nulla, mollis id ultricies quis, dictum at mi. Nunc gravida eros non odio congue non vehicula eros ultrices. Nam nec rutrum magna. In eu sem tellus, at sodales odio. Maecenas placerat, neque et ornare varius, ipsum ante tincidunt dolor, vel tincidunt risus orci at quam. Suspendisse potenti. Morbi dapibus libero quam. Etiam ac dui a nulla adipiscing suscipit eu in eros. Nam a quam ut sem volutpat sagittis eu eu neque. Fusce auctor, diam a laoreet auctor, leo quam adipiscing sapien, et consequat lectus tortor in mauris. Nulla enim nisl, pharetra id congue a, fermentum a est. Fusce dictum faucibus urna, in cursus justo imperdiet vitae. Praesent nulla lectus, consectetur nec cursus eleifend, molestie viverra quam. Ut dictum pellentesque ante, ut egestas risus tristique a. Duis eget lorem blandit augue ornare volutpat. Curabitur ac justo nisi, in mattis sapien.

Donec bibendum tempor nibh. Nunc posuere, eros at hendrerit dapibus, mauris velit congue sapien, non varius dolor mauris et libero. Aliquam id quam lacus, et luctus nisi. Duis sit amet nibh a nisl dapibus faucibus eu sit amet purus. Curabitur malesuada volutpat malesuada. In hac habitasse platea dictumst. Mauris iaculis turpis sit amet massa fringilla condimentum. Ut eget arcu nulla. Vestibulum ut sem et urna molestie suscipit. Mauris dapibus, magna et iaculis ornare, felis felis hendrerit nibh, vitae consequat orci erat a nisi. Nunc ut diam dolor, quis consectetur augue. Praesent auctor euismod elit quis ultrices. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ut felis non ante placerat auctor. Nulla a ligula nunc. In at massa quis diam commodo placerat at sit amet orci. Pellentesque velit turpis, rutrum id semper id, volutpat sed lacus.

Fusce dapibus volutpat erat, vel facilisis neque rhoncus eget. Aliquam sodales sollicitudin libero a condimentum. Phasellus eu risus sit amet erat rhoncus consequat id quis mauris. Nam sed risus urna. Donec urna enim, aliquet at adipiscing id, rhoncus eu eros. Morbi vestibulum cursus lectus eget dapibus. Sed fermentum erat a quam vehicula id semper nunc volutpat. Phasellus nisl erat, hendrerit eget iaculis id, accumsan ut quam. Sed viverra sem eget metus commodo eget pretium metus sodales. Maecenas elit neque, tincidunt sit amet eleifend mattis, viverra non enim. Proin molestie venenatis massa, quis facilisis ipsum vulputate ut. Nulla ut purus lectus, ac faucibus ante. Phasellus adipiscing rhoncus dolor, in tristique metus blandit vitae. Vestibulum interdum, metus lacinia semper imperdiet, purus neque vulputate arcu, quis tempus augue purus et turpis. Donec augue purus, porttitor in facilisis non, posuere ac velit.

Donec erat eros, hendrerit ac ultricies vitae, feugiat at massa. Nam non dolor in elit vestibulum interdum. In hac habitasse platea dictumst. In imperdiet, quam sit amet auctor molestie, lectus augue dictum nibh, eget porta erat turpis sit amet diam. Etiam nec erat quis quam placerat placerat eu quis sem. Quisque tincidunt turpis eu nibh pulvinar at rhoncus lectus faucibus. Suspendisse potenti. Nunc placerat auctor pulvinar. Morbi tincidunt velit eu augue suscipit sit amet iaculis enim luctus. Curabitur auctor lectus sed arcu condimentum et malesuada nunc sodales. Curabitur molestie, tortor non scelerisque porta, odio nisi auctor orci, id elementum dui massa at nulla. In porta tellus ac nulla vestibulum tempus a eu sem. Ut pharetra diam mauris. Quisque eu ligula erat. In hac habitasse platea dictumst. Vivamus egestas facilisis libero, at placerat lorem scelerisque at. In vehicula neque vel sapien imperdiet sodales. Fusce at pulvinar odio.

Donec ipsum nunc, vulputate at interdum in, suscipit ac augue. Quisque leo tellus, accumsan interdum rhoncus non, feugiat in neque. Praesent lobortis dui nec magna euismod iaculis. Vestibulum malesuada rhoncus lacus, ac pretium ipsum feugiat ut. Curabitur malesuada lorem eu sem ultrices nec imperdiet odio semper. Sed tristique gravida neque, non imperdiet metus consequat non. Aliquam mattis tempor dignissim. Sed vulputate sollicitudin posuere. Maecenas tincidunt tellus et arcu ullamcorper lobortis. Donec iaculis scelerisque euismod. Fusce urna leo, tincidunt sed dignissim eget, varius et dui. Nullam vestibulum, tellus sed dictum laoreet, lorem dolor mattis odio, sit amet consequat diam arcu et risus. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id volutpat turpis. Duis ac nunc eget neque posuere elementum sed non ipsum. In hac habitasse platea dictumst. Donec ipsum mi, porttitor in elementum non, placerat ut nulla.

Sed facilisis faucibus nisl vitae vulputate. Integer dictum diam a enim egestas facilisis. Nulla in eros et felis venenatis adipiscing quis vitae est. Integer sollicitudin felis eu sem vulputate sit amet sodales augue congue. In vehicula egestas malesuada. Suspendisse congue, magna a ultricies euismod, neque nibh rhoncus lorem, a congue tortor magna sit amet velit. Proin est magna, ornare eget posuere at, sagittis sit amet tellus. Vivamus eleifend lorem diam. Sed vel neque ligula, ut pulvinar velit. Donec vel rutrum dolor. Nulla bibendum diam eu mi pretium aliquam. Donec at elit et ipsum posuere varius. Curabitur mi lectus, bibendum viverra sodales vel, fringilla vitae lectus. Praesent quis lacus massa. Sed sagittis sem eget risus gravida ut suscipit turpis porttitor. Maecenas ac eros vehicula libero semper auctor.

Aliquam laoreet auctor suscipit. Quisque laoreet justo id dolor egestas ornare fringilla tellus egestas. Phasellus eu porta velit. Mauris porttitor nunc nec leo tincidunt scelerisque. Donec placerat odio at metus hendrerit rhoncus. Vivamus eleifend volutpat lorem eu dapibus. Vivamus semper imperdiet faucibus. Etiam ante felis, placerat a mollis nec, elementum et dui. Mauris pellentesque, odio vel viverra vehicula, odio dui eleifend sapien, in fringilla mauris enim a ligula. Nunc quis odio eu ipsum congue ultricies. Integer in odio odio. Phasellus et nibh quam. In sodales dignissim metus, ac pulvinar justo sodales id.

Nulla massa libero, vulputate et tempor eget, fringilla eu eros. Maecenas ultricies viverra condimentum. Ut nisl enim, vulputate a tempor a, iaculis vel enim. Cras vel metus eu magna blandit pulvinar eget ut nunc. Fusce eget semper nisi. Quisque elementum justo dapibus neque dapibus non aliquet quam viverra. Proin in turpis vehicula velit hendrerit commodo. Aliquam elit libero, scelerisque a dapibus sed, adipiscing dapibus purus. Fusce at diam vitae purus imperdiet pellentesque. Aenean posuere varius arcu, et accumsan sem porttitor vitae. Quisque libero leo, gravida eget dictum id, bibendum eget nisl.

Aenean metus nibh, pretium id lobortis id, faucibus eget mauris. Suspendisse tempus, sem ut auctor molestie, nulla velit consectetur nibh, nec egestas eros velit vitae eros. Maecenas cursus quam eget lorem sodales nec aliquam libero tincidunt. Quisque libero tortor, iaculis at convallis eu, facilisis in mi. Integer adipiscing magna vitae justo viverra tincidunt. Sed vel lacus consectetur enim malesuada gravida sit amet et erat. Sed metus sapien, imperdiet in sodales a, gravida eu tellus. Nam facilisis felis eu ipsum aliquet commodo. Nunc ullamcorper auctor cursus. Etiam congue urna in tellus feugiat malesuada. Nullam consectetur est in nisi porttitor pharetra consectetur libero sollicitudin. Nulla scelerisque eleifend arcu vitae dapibus. Donec ac dictum dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed faucibus, felis quis aliquet elementum, tellus enim pellentesque ante, eget sollicitudin mi tellus sit amet odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Pellentesque pharetra libero sed urna consequat id tincidunt turpis sollicitudin. Integer vulputate massa nec sem ultrices feugiat. Phasellus ullamcorper, augue eget sodales aliquam, leo quam lacinia est, ac bibendum velit nunc vitae lacus. Phasellus fringilla, augue non varius pharetra, velit mi vulputate magna, sit amet luctus velit mauris at urna. In eleifend venenatis leo, sed eleifend urna commodo et. Sed tortor nisi, rutrum a dictum sit amet, auctor lacinia sapien. Suspendisse vestibulum enim vitae lorem tempor eget tincidunt urna luctus. Proin feugiat dolor ut elit laoreet quis pellentesque purus rhoncus. Nullam in feugiat nisi. Vestibulum nec vehicula nibh. Morbi dignissim pellentesque erat, non tempor ante lobortis et. Phasellus massa risus, adipiscing quis viverra ac, consectetur vitae lacus. Aliquam eleifend nulla at lectus sollicitudin congue. Praesent luctus, ipsum suscipit egestas condimentum, libero risus consequat turpis, venenatis venenatis lorem nisl id sapien. Etiam nec sem at tellus vestibulum lobortis. Ut vel tellus et ligula congue hendrerit facilisis vitae ipsum. Sed quis convallis velit. 
HEREE
},{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."},
{ :title => 'Anna Karenina', :author => Author.find_by_name("Leo Tolstoy"), :edit_count => 0,
 :body => "A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."}
])
